import datetime
import json


def generate_new_log(timestamp, log_info, status_code):
    '''
    This function is responsible for generating a new log when called.
    
    Parameters: 
        timestamp: the exact time when action was preformed which is generated by the get_est_timestamp() function.
        log_info: description of action
        status_code: 200 if successful action, 400 if unsuccessful or invalid.
    
    '''
    log = {
        timestamp : {
            "log_info" : log_info,
            "status_code" : status_code
        }
    }
    return log


def dump_to_log_file(new_data):
    '''
    This function is responsible for adding a log to json file after being generated.
    
    Parameters:
        new_data: the log needing to be added to log file
    
    '''
    with open('ru_snipez_logs.json ', 'r') as file:
        data = json.load(file)

    data.update(new_data)
    
    with open('ru_snipez_logs.json', 'w') as file:
        json.dump(data, file, indent=4)


def get_est_timestamp():
    '''
    This function is responsible for generating a real-time EST standard timestamp. 
    '''   
    est_offset = datetime.timedelta(hours=4)
    utc_timestamp = datetime.datetime.utcnow()
    est_timestamp = utc_timestamp - est_offset
    timestamp_str = est_timestamp.strftime('%m-%d-%Y %I:%M:%S %p EST%Z')
    return timestamp_str